# Generated by Django 5.0.6 on 2024-07-03 19:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GroceryImage",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Grocery Image",
                "verbose_name_plural": "Grocery Images",
                "db_table": "grocery_images",
                "ordering": ["file_name"],
            },
        ),
    ]
