# Generated by Django 5.0.6 on 2024-07-03 19:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grocery_store", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroceryCard",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grocery_image",
                        to="grocery_store.groceryimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grocery Card",
                "verbose_name_plural": "Grocery Cards",
                "db_table": "grocery_cards",
                "ordering": ["name"],
            },
        ),
    ]
