# Generated by Django 5.0.6 on 2024-07-03 20:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_store', '0002_grocerycard'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryStore',
            fields=[
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Grocery Store',
                'verbose_name_plural': 'Grocery Stores',
                'db_table': 'grocery_stores',
                'ordering': ['name'],
                'unique_together': {('name', 'address')},
            },
        ),
    ]
