# Generated by Django 5.0.6 on 2024-07-03 20:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_store', '0003_grocerystore'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardInGroceryStore',
            fields=[
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining', models.PositiveIntegerField(default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery_store.grocerycard')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery_store.grocerystore')),
            ],
            options={
                'verbose_name': 'Card In Grocery Store',
                'verbose_name_plural': 'Cards In Grocery Store',
                'db_table': 'card_in_grocery_stores',
                'ordering': ['store', 'card'],
                'unique_together': {('card', 'store')},
            },
        ),
    ]
